## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName
    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

class _ARRW:
     def __init__(self, obj, index):
         self.obj = obj
         self.index = index
     def __lshift__(self, r):
         self.obj[self.index] = r

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 3) import stages.ep_commonlib as cl;
from stages import ep_commonlib as cl
# (Line 5) var iflag = 0;
iflag = EUDCreateVariables(1)
_IGVA([iflag], lambda: [0])
# (Line 6) var angle = 0;
angle = EUDCreateVariables(1)
_IGVA([angle], lambda: [0])
# (Line 7) var t = 0;
t = EUDCreateVariables(1)
_IGVA([t], lambda: [0])
# (Line 8) const dt = 1;
dt = _CGFW(lambda: [1], 1)[0]
# (Line 10) var subt = 0;
subt = EUDCreateVariables(1)
_IGVA([subt], lambda: [0])
# (Line 12) function pattern() {
@EUDFunc
def f_pattern():
    # (Line 13) if (iflag == 0) {
    if EUDIf()(iflag == 0):
        # (Line 15) iflag = 1;
        iflag << (1)
        # (Line 16) }
        # (Line 18) subt++;
    EUDEndIf()
    subt.__iadd__(1)
    # (Line 19) if(subt == 2) {
    if EUDIf()(subt == 2):
        # (Line 20) subt = 0;
        subt << (0)
        # (Line 22) const cx, cy = cl.getTilePos(2, 2);
        cx, cy = List2Assignable([cl.f_getTilePos(2, 2)])
        # (Line 23) for(var i = 0 ; i < 4 ; i++) {
        i = EUDVariable()
        i << (0)
        if EUDWhile()(i < 4):
            def _t4():
                i.__iadd__(1)
            # (Line 24) const a = angle + i * 90;
            a = angle + i * 90
            # (Line 25) const cdx, cdy = lengthdir(50, a);
            cdx, cdy = List2Assignable([f_lengthdir(50, a)])
            # (Line 26) cl.mloc_px($L('cloc1'), cdx + cx, cdy + cy, -22);
            # (Line 27) const dx1, dy1 = lengthdir(600, a);
            cl.f_mloc_px(GetLocationIndex('cloc1'), cdx + cx, cdy + cy, -22)
            dx1, dy1 = List2Assignable([f_lengthdir(600, a)])
            # (Line 28) const ddx, ddy = cl.getInfiniteVectorEnd(cx, cy, dx1, dy1);
            ddx, ddy = List2Assignable([cl.f_getInfiniteVectorEnd(cx, cy, dx1, dy1)])
            # (Line 29) cl.mloc_px($L('cloc2'), ddx, ddy, 0);
            # (Line 30) CreateUnit(1, 'Small Missile', 'cloc1', P7);
            cl.f_mloc_px(GetLocationIndex('cloc2'), ddx, ddy, 0)
            # (Line 31) Order('Small Missile', P7, 'cloc1', Move, 'cloc2');
            # (Line 32) }
            DoActions([
                CreateUnit(1, 'Small Missile', 'cloc1', P7),
                Order('Small Missile', P7, 'cloc1', Move, 'cloc2')
            ])
            # (Line 33) cl.mloc_px($L('cloc1'), cx, cy, 0);
            EUDSetContinuePoint()
            _t4()
        EUDEndWhile()
        # (Line 34) CreateUnit(1, "Flare", 'cloc1', P7);
        cl.f_mloc_px(GetLocationIndex('cloc1'), cx, cy, 0)
        # (Line 35) KillUnitAt(All, 'Flare', 'Anywhere', P7);
        # (Line 37) KillUnitAt(All, 'Small Missile', 'u', P7);
        # (Line 38) KillUnitAt(All, 'Small Missile', 'l', P7);
        # (Line 39) KillUnitAt(All, 'Small Missile', 'd', P7);
        # (Line 40) KillUnitAt(All, 'Small Missile', 'r', P7);
        # (Line 42) angle = (angle + t) % 360;
        DoActions([
            CreateUnit(1, "Flare", 'cloc1', P7),
            KillUnitAt(All, 'Flare', 'Anywhere', P7),
            KillUnitAt(All, 'Small Missile', 'u', P7),
            KillUnitAt(All, 'Small Missile', 'l', P7),
            KillUnitAt(All, 'Small Missile', 'd', P7),
            KillUnitAt(All, 'Small Missile', 'r', P7)
        ])
        angle << ((angle + t) % 360)
        # (Line 43) t += dt;
        t.__iadd__(dt)
        # (Line 44) if (t >= 360) t -= 360;
        if EUDIf()(t >= 360):
            t.__isub__(360)
            # (Line 45) }
        EUDEndIf()
        # (Line 46) }
    EUDEndIf()
