stagelist_hard = [
    ('pattern01_var1',    '간단폭피'),
    ('pattern16',         '달려달려'),
    # ('pattern04',         '우향우'),
    # ('pattern11_var1',    '다다해악'),
    # ('pattern52_var2',    '추가패턴3'),
    ('pattern49',         '자전'),
    # ('pattern37_var2',    '큰배사이로'),  → Modify
    ('pattern02',         '미꾸라지'),
    ('pattern37_var1',    '지그재그길'),
    # ('pattern06_var2',    '파일런길막기'),
    # ('pattern58',         '불협화음'),
    # ('pattern66',         '빙글빙글'),
    # ('pattern69',         '회오리'),
    ('pattern56_var1',    '태양피하기'),
    # ('pattern55_var1',    '마름모뜷기'),
    # ('pattern54_var1',    '랜덤교차지점'),
    ('pattern65',         '비트섬'),
    # ('pattern05',         '귀소본능'),
    ('pattern54_var2',         '교차지점'),
    ('pattern32',         '융단폭격'),
    ('pattern64',         '시정지'),
    # ('pattern14',         '반칸교대'),
    ('pattern22_var1',    '느림의 미학'),
    ('pattern71',         '돌피하기'),
    ('pattern63',         '각설이또옴'),
    ('pattern17',         '천천히'),
    ('pattern63_var2',    '사구체'),
    ('pattern34',         '애매모호'),
    # ('pattern13',         'now Right'),
    ('pattern07_var2',    '육계단'),
    ('pattern68',         '위 아래'),
    ('pattern70',         '게장'),
    ('pattern18',         '프로길막러'),
    ('pattern07_var3',    '계단의 미학'),
    # ('pattern23_var4',    '반칸랜덤'),
    ('pattern09_var3',    '역반칸무빙'),
]
