stagelist_hard = [
    # ('pattern01_var4', '간단한 폭탄피하기'),
    ('pattern65', '비트섬'),  # ('pattern45', '대각선 바둑판'),
    # ('pattern51', '관성의 법칙'),
    ('pattern69', '회오리'),  # ('pattern29', '역주행'),
    # ('pattern39_var1', '마이크로마우스'),
    # ('pattern09_var1', '반칸 미사일'),
    ('pattern22', '느림의 미학'),  # ('pattern57', '양쪽에서 일자미사일'),
    # ('pattern52', '사이비팩 보너스패턴 변형'),
    ('pattern64', '시정지'),  # ('pattern44', 'TimeLock'),
    # ('pattern24', '8방향 폭탄피하기'),
    # ('pattern09_var2', '십자 반칸 미사일'),
    # ('pattern52_var1', '사이비팩 보너스패턴 변형 2'),
    # ('pattern30', '발키리 피하기'),
    ('pattern23_var4', '불규칙'),  # ('pattern23', '이중랜덤 미사일'),
    # ('pattern06', '해처리 길막 연습'),
    # ('pattern25', '이상한 가로미사일'),
    # ('pattern50', '좁아터진 길'),
    # ('pattern22', '사방에서 울'),
    # ('pattern01_var2', '90도 뒤집은 폭탄피하`기'),
    # ('pattern21', '신도림 환승역'),
    # ('pattern11_var2', '가로세로 복합패턴'),
    # ('pattern26_var1', '좁아터진 빙빙돌기'),
    # ('pattern15', '타이밍생 타이밍사'),
    # ('pattern40_var1', '무궁화꽃이거꾸로피었습니다'),
    # ('pattern37', '매트릭스'),
    # ('pattern54_var2', '스카웃과 배틀 피하기'),
    # ('pattern42', '격자 맞춰 사이드의 진헌곡'),
    ('pattern68', '위 아래'),  # ('pattern36', '사이드스텝'),
    ('pattern67', '사면초가'),  # ('pattern55', '컨베이어 벨트 돌리기'),
    # ('pattern38', '쌍대각선 미사일'),
    # ('pattern12', '8방향에서 날라오는 미사일'),
    # ('pattern31', '줄세우기'),
    # ('pattern10', '좁은간격 실전'),
    # ('pattern23_var2', '랜덤 미사일'),
    # ('pattern07_var1', '사방에서 스테이지'),
    # ('pattern30_var1', '발키리 피하기 2'),
    # ('pattern28', '소나기'),
    ('pattern66', '빙글빙글'),  # ('pattern27', '45도 결맞는 미사일'),
    # ('pattern53', '역방향 교차 계단'),
    # ('pattern09', '사이드 반칸무빙'),
    # ('pattern65', '랜덤으로 흩뿌리기'),
    # ('pattern66', '양옆 스테이지'),
    # ('pattern67', '무한 스테이지'),
]
