stagelist_easy = [
    # ('pattern45_var1', '대각선 뜷기'),
    ('pattern51_var2', '역방향 관성의 법칙'),
    ('pattern39_var2', '마이크로마우스2 쉬운버젼'),
    ('pattern01_var4', '돌아돌아'),
    ('pattern09_var2_var1', '십자 미사일'),
    ('pattern57_var1', '사인파'),
    # ('pattern09_var1_var1', '한칸씩 미사일'),
    ('pattern01', '간단한 폭탄피하기'),
    ('pattern52_var3', '사이비팩 보너스패턴 변형'),
    ('pattern07', '사방에서 스테이지'),
    ('pattern23_var1', '랜덤 미사일'),
    ('pattern29_var1', '역주행'),
    ('pattern52_var1_var1', '사이비팩 보너스패턴 변형 2'),
    ('pattern44_var1', 'TimeLock'),
    ('pattern50_var1', '좁아터진 길'),
    ('pattern40', '무궁화꽃이피었습니다'),
    # ('pattern55_var1', '컨베이어 벨트 돌리기'),
    ('pattern24_var1', '4방향 폭탄피하기'),
    ('pattern46', '대각선 미사일 폭탄 피하기'),
    ('pattern57', '좌우에서 울'),
    ('pattern09_var1_var2', '반칸 미사일 무빙'),
    ('pattern38_var1', '대각선 사이드의 진헌곡'),
    ('pattern28_var1', '소나기 (쉬움)'),
    ('pattern62', '발키리 피하기'),
    ('pattern23', '이중랜덤 미사일'),
    ('pattern10_var1', '좁은간격 실전'),
    ('pattern36_var1', '좌우로 왔다갔다'),
    ('pattern25_var1', '이상한 가로미사일'),
    # ('pattern37_var1', '매트릭스 (쉬움)'),
    ('pattern31_var1', '줄세우기'),
    # ('pattern11_var2', '가로세로 복합패턴'),
    ('pattern15_var1', '타이밍생 타이밍사'),
    ('pattern54_var3', '스카웃과 배틀 피하기'),
    ('pattern63_var1', '틈 뚫기'),
    ('pattern30', '발키리 피하기 2'),
    ('pattern26', '좁아터진 빙빙돌기'),
    ('pattern27_var1', '45도 결맞는 미사일'),
    ('pattern58_var1', '상하 랜덤미사일 피하기'),
    ('pattern06_var1', '해처리 길막 연습'),
    ('pattern12_var1', '4방향에서 날라오는 미사일'),
]
