import re


def ConvertTrigEditPlusTrigger(s):
    # Trigger fields
    s = re.sub(r"^Trigger {", "Trigger(", s, flags=re.MULTILINE)
    s = re.sub(r"^    players = \{(.+)\},\n", "    players=[\\1],\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    conditions = \{\n", "    conditions=[\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    actions = \{\n", "    actions=[\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    flags = {(.+)},\n", "    flags=[\\1],\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    },\n", "    ],\n", s, flags=re.MULTILINE)
    s = re.sub(r"},\n\}", ")", s, flags=re.MULTILINE)
    s = re.sub(r"^        (.+);\n", "        \\1,\n", s, flags=re.MULTILINE)
    s = re.sub(r"--(.+)", "#\\1", s)  # comments
    s = re.sub(r"\n*# This text is generated by TrigEditPlus\n*", '', s)
    s = re.sub(r"\n{3,}", "\n\n", s)
    return s
